### ISSUE TITLE
'x-async-responses' is not defined at 3scale_toolbox

### ISSUE THREAD

**Issue by ypreiger** [3scale/3scale_toolbox#105]
**Here is the issue as it described by the customer:
I’m testing 3scale_toolbox at this moment as found this tool useful to import yaml files into 3scale (curl and ui allows only json format).

By the way, when I tried to import our swagger file next message appears:
[root@vpudov swagger]# 3scale import openapi -d https:// 3scale-cm-admin.magic.telekom.de/ external-swagger.yaml
Error: OpenAPI schema validation failed: Cannot coerce property "post" from Hash to Swagger::V2::Operation: The property 'x-async-responses' is not defined for Swagger::V2::Operation.
[root@vpudov swagger]# cat external-swagger.yaml | grep -A 2 "x-async-responses"
      x-async-responses:
        callback: "receiveUpdateGfAp"
  /resource-order-resource-inventory/v1/llc:
--
      x-async-responses:
        callback: "receiveLlcInfo"
  /resource-order-resource-inventory/v1/llc/async/put:
--
      x-async-responses:
        callback: "receiveUpdateLlc"
  /resource-order-resource-inventory/v1/llc/connect:
--
      x-async-responses:
        reference-operation-id: "updateGfApAsync"
  /callback/ponInventory/v1/llc/get:
--
      x-async-responses:
        reference-operation-id: "getLlcInfoAsync"
  /callback/ponInventory/v1/llc/put:
--
      x-async-responses:
        reference-operation-id: "updateGfApAsync"
definitions:
[root@vpudov swagger]#
[root@vpudov swagger]# 3scale -v
0.7.0
[root@vpudov swagger]#
 Based on Swagger doc:
The extensions properties are always prefixed by "x-" and can have any valid JSON format value.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#specification-extensions

When we tried to send the same swagger but only in json format through ui, for example, there is no problem.

[external-swagger.yaml.txt](https://github.com/3scale/3scale_toolbox/files/2961063/external-swagger.yaml.txt)
Swagger.yaml file in attachement.**

**Comment by eguzki** [comment]
Working on this. 

After fixing (locally in my dev environment), your spec file was rejected by 3scale. `host` field cannot be `localhost`
