### ISSUE TITLE
<spec> usage not specified on the help command for import openapi

### ISSUE THREAD

**Issue by hguerrero** [3scale/3scale_toolbox#107]
There is no information in the help command regarding the information on where should the file be neither the type (json,yml) for the spec.

**Comment by eguzki** [comment]
Could you open PR? 

You just need to update `summary` and/or `usage` and/or `description`

https://github.com/3scale/3scale_toolbox/blob/master/lib/3scale_toolbox/commands/import_command/openapi.rb#L24

Just in case you did not know, it is documented in docs https://github.com/3scale/3scale_toolbox/blob/master/docs/openapi.md, but not available in help command, indeed.
