### ISSUE TITLE
ActiveDocs created in "hidden" state and there is no switch to make it visible

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/3scale_toolbox#108]
# Current behavior

When I'm importing an OpenAPI Spec using the `master` branch:
```raw
$ bundle exec 3scale import openapi examples/echo-api.yaml -d nmasse-redhat -t echo_api
Updated service id: 2555417776440, name: Echo API
destroying all mapping rules
Created GET /$ endpoint
```

The ActiveDocs is created in "hidden" state and there is no switch in the `3scale import openapi` to make it visible:
<img width="1000" alt="Screen Shot 2019-03-14 at 16 57 10" src="https://user-images.githubusercontent.com/7472564/54371779-48a15d80-467a-11e9-8665-d29d14fc8c8b.png">

# Expected behavior

The `3scale import openapi` command creates/updates the ActiveDocs and it is visible by default.

**Comment by mikz** [comment]
@nmasse-itix it is not possible to make it visible on the edit form?

**Comment by eguzki** [comment]
it is, but requires manual step

**Comment by nmasse-itix** [comment]
Tested #109: works for me 👍
