### ISSUE TITLE
Ideas for future commands to add (for discussion)

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/3scale_toolbox#11]
Not intended to be implemented, just interested in hearing what commands people would find useful in the toolbox. Then some of us could volunteer to try implementing some of them, or prototype them at least....contributing to grow our own toolbox...

The idea is that these would be useful for us and also for providers.

"3scale login" (like heroku toolbelt). It takes provider_key/token and domain, and stores (in ENV? in CWD?) who you are as a provider, and you don't need to send provider key and domain with each command?

"3scale account" Dumps information about the account identified via key/domain. When created, admin and member users, etc.

"3scale whois" Takes an identified (any of user_key?, email? name?) and uses the API to tell you who that is...User info, on what account, a provider user or developer etc... May involve searching using multiple methods, depending if it can distringuish what type of key was provided.

"3scale invoices" Return a set of invoices for a specified time period, in cvs/json/xml format.

"3scale stats" Return data on defined metrics for a given service & time period in csv/json/xml format.

**Comment by eguzki** [comment]
Closing old issues
