### ISSUE TITLE
SAP OpenAPI Specification file cannot be imported

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/3scale_toolbox#111]
# Current Behavior

When importing this [SAP OpenAPI Specification file](https://api.sap.com/api/analytics_reporting_view/overview?name=analytics_reporting_view&amp;type=JSON&amp;action=download&amp;artifactType=REST), the toolbox encounters multiple issues:
- it fails to validate the OpenAPI Specification file and thus exits without doing anything

```raw
$ 3scale import openapi -t sap_api -d https://$ACCESS_TOKEN@$TENANT-admin.3scale.net examples/analytics_reporting_view.yaml 
Error: OpenAPI schema validation failed: The property '#/securityDefinitions/OAuth2' of type object did not match any of the required schemas
```

- if the OpenAPI Specification is changed to fix the previous error, the 3scale toolbox fails with:

```raw
$ 3scale import openapi -t sap_api -d https://$ACCESS_TOKEN@$TENANT-admin.3scale.net examples/analytics_reporting_view.yaml 
Created service id: 2555417777839, name: Analysis Reporting View Management API
Error: Metohd has not been saved. {"system_name"=>["invalid"]}
```

# Expected Behavior

The 3scale toolbox detects the provided file does not match the OpenAPI Specification 2.0 JSON Schema and prints an error message. 

The command is re-run with an additional parameter to skip the OpenAPI Specification validation. When the ActiveDocs is created or updated, the `skip_swagger_validations` field is set to `true`. 

The `operationId` field is properly sanitized to be used as a system_name. 

# Business Justification

SAP is an important partner for Red Hat and an important software editor for our customers. Their OpenAPI Specification files do not fully conform to the JSON schema but it is a very common case since OAS is very slow to integrate RFEs from the community. In fact, most OAS files found on customer site, at some point in time, do not fully conform to the OAS. 

Copy of the SAP OpenAPI Specification file is provided here:

```raw
https://gist.github.com/nmasse-itix/74919993967a8083345d8fa2f40b0b0a
```

**Comment by andrewdavidmackenzie** [comment]
When  I just tried to view/download it.... it required a login to be able to access it.
Are you sure the toolbox can actually access the file?

**Comment by nmasse-itix** [comment]
Yes, I know you have to register to download the SAP OAS and this is why I provided a copy for @eguzki:

> Copy of the SAP OpenAPI Specification file is provided here:
> 
> ```
> https://gist.github.com/nmasse-itix/74919993967a8083345d8fa2f40b0b0a
> ```
