### ISSUE TITLE
provide an executable of the toolbox

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale_toolbox#122]
we are requiring Ruby language to be installed to use this toolbox, which can be a big limitation especially if being used directly by systems.
I suggested packaging the toolbox as an executable, I did it myself by leveraging this tool

https://github.com/pmq20/ruby-packer

and executing this command

rubyc --gem=3scale_toolbox --gem-version=0.7.0 3scale

**Comment by eguzki** [comment]
https://github.com/3scale/3scale_toolbox_packaging/releases/latest

You have installers for
* MacOS
* Windows
* RPM based linux distro (x64) like centos
* Deb based linux distro like Ubuntu
* Docker images

No dependencies on host O.S. not even ruby to be installed.

**Comment by eguzki** [comment]
There was an issue on windows support https://github.com/3scale/3scale_toolbox/pull/113 and that's why windows package is not available on release 0.7.0. The issue has been fixed and already merged to upstream master.

We will release 0.8.0 soon to include windows package

**Comment by eguzki** [comment]
I consider this issue as closed @lucamaf 

Feel free to do that when you checkout available packages and see ruby is not required to be installed for the toolbox to work.

**Comment by lucamaf** [comment]
thank you!
