### ISSUE TITLE
Provide some utility methods to command writers

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/3scale_toolbox#14]
Heh..... looking at existing commands and playing with writing a new one..... I suspect there will be some code that will be repeated across many commands?

Examples:
- Command/option parsing and help printing
- API url manipulation

On that second one, I see these two methods:

> def provider_key_from_url(url)
>   URI(url).user
> end
> 
> def endpoint_from_url(url)
>   uri      = URI(url)
>   uri.user = nil
> 
>   uri.to_s
> end

These could be provided by a shared class? (cli?)

Maybe even parsing of a "standard" url used for many commands ("source") could be done in a common file too? Get a tuple of key,url back, or even a Client object directly - all ready to talk to that source API....?

**Comment by mikz** [comment]
Yes. We will be creating 3rd command for #22 so it would make sense to extract the all shared code to some util class.

**Comment by eguzki** [comment]
Closing it. Utility methods are available.
