### ISSUE TITLE
Manage integration with the Auth provider (keycloak) 

### ISSUE THREAD

**Issue by hguerrero** [3scale/3scale_toolbox#148]
Add features to configure zync service account and been able to create users and integration with the default Auth implementation RH SSO (keycloak) when protecting a service with OpenID Connect

**Comment by eguzki** [comment]
Could you specify more? 

What steps should the toolbox logic have implemented? Which API's should use?

**Comment by sekharvajjhala** [comment]
@hguerrero Can you provide more details on this feature request ?

**Comment by eguzki** [comment]
closing for no answer
