### ISSUE TITLE
Cannot import mapping rules to services

### ISSUE THREAD

**Issue by VinayBhalerao** [3scale/3scale_toolbox#15]
Followed the master dev instructions https://github.com/3scale/3scale_toolbox/blob/master/docs/import.md

After I ran the command on my test account, it created a service with methods, but not mapping rules

**Command:**
bundle exec exe/3scale import csv --destination=https://<provider_key>@foobar-admin.3scale.net --file=import_endpoints.csv

**Log:**
Method v1_Taxing_RecalculateTax has been created.
Method v1_Lead_Leads has been created.
Method v1_Products_GetProducts has been created.
Method v1_Products_GetCompanyList has been created.
Method SupplierInfo_Supplier has been created.
Method v2_Product_GetProductEligibility has been created.
....
....
....
....

1 services in CSV file
1 services have been created
0 metrics have been created
25 methods have beeen created

[Link](https://www.dropbox.com/s/81dp4jnyoqw6a2x/import_endpoints.csv?dl=0) to download the import_endpoints.csv

Expected result:
Create mapping rules and map that to http method name (Verb) and application plan method name (Metric or Method) in Integrations tab.

**Comment by macejmic** [comment]
should be fixed but better to test it first and then release a new version of the gem.

**Log:**
...
1 services in CSV file
1 services have been created
0 metrics have been created
25 methods have beeen created
25 mapping rules have been created

can you test it please by yourself and confirm/decline if everything's fine? (branch: 15-mapping-rules)

@VinayBhalerao

**Comment by VinayBhalerao** [comment]
👍
