### ISSUE TITLE
The 3scale application apply/create is missing an option to set the redirect url

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/3scale_toolbox#178]
# Current behavior

The `3scale application apply` and `3scale application create` commands are missing an option that is needed for end-to-end scenario using OpenID Connect: an option to set the redirect_url(s) of the application (otherwise the standard and implicit flow cannot work)

# Expected behavior

```sh
3scale application apply nmasse-redhat client-id --application-key=my-client-secret --name=my-app --plan=basic --service=api --redirect_url=https://sample.url/callback --redirect_url=https://another.url/callback
```

**Comment by eguzki** [comment]
@nmasse-itix Should the toolbox validate those URL(s) for valid URL format?

**Comment by eguzki** [comment]
@nmasse-itix More than one `redirect_url` are allowed?

**Comment by nmasse-itix** [comment]
@eguzki Multiple redirect URLs are allowed in RH-SSO but not in 3scale. So only one redirect URL. 👍

**Comment by nmasse-itix** [comment]
> @nmasse-itix Should the toolbox validate those URL(s) for valid URL format?

If we want to validate the URL, we have to be very cautious not to be too restrictive. Mobile apps for examples can use other schemes than http(s) for their redirect url.

Given that we don't use this value internally for the toolbox but instead just pass it as-is to the system, I would not apply a double validation here. what do you think ?

**Comment by eguzki** [comment]
Fair enough, toolbox will pass as-is :+1:
