### ISSUE TITLE
Add proxy configuration update

### ISSUE THREAD

**Issue by ppatierno** [3scale/3scale_toolbox#202]
As there are commands for listing, promoting and showing proxy configuration it could be useful to have the update as well (it's provided by the API).

**Comment by eguzki** [comment]
Proxy configuration consists of many parameters grouped in mapping rules, auth settings, policies and so on. Could you be more specific? Which parameters and optional params would the command have?

**Comment by ppatierno** [comment]
I guess that all the ones you listed are useful. For sure the policies, I had to use the cURL command for doing so.
