### ISSUE TITLE
to_h method undefined when copy a service

### ISSUE THREAD

**Issue by agouz** [3scale/3scale_toolbox#24]
Hello team,

I've encountered the following error while trying to run the copy command on a service.

"to_h" method is undefined.

It worked after removing "to_h" from "end.to_h" @ Line 167 in 3scale-copy file (3scale_toolbox-0.2.2/exe)

**Comment by mikz** [comment]
@agouz what version of Ruby you are using? It was added in Ruby 2.1.

We should explicitly declare that version dependency. More things will be broken.

Will do a new release after merging #25.

**Comment by agouz** [comment]
I am using "ruby 2.0.0p648"....
I just followed the installation instruction found in the read me file.

**Comment by mikz** [comment]
Ruby 2.0 reached its end of life (https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/). 
I'd suggest to update your Ruby version. We can't promise our code works on Ruby 2.0 because we are not testing against it anymore.

**Comment by agouz** [comment]
Thanks a lot

**Comment by mikz** [comment]
We should consider making a package that would have own Ruby. Proposed in #26.
But that will take time. So you can keep track of that issue if you'd like to get notified when that is done.
