### ISSUE TITLE
import openapi "--override-private-basepath" param strange behavior

### ISSUE THREAD

**Issue by vvidovic** [3scale/3scale_toolbox#248]
It seems that setting "--override-private-basepath" param on "3scale import openapi" command doesn't set Path value for the used backend. The version I am using is 0.16.0 for Linux/Ubuntu.
I would expect the same behavior as when using the following curl command:
```
curl -k -X PUT "https://3scale-admin.nnnn.net/admin/api/services/${api_id}/backend_usages/${back_id}.json" -F "access_token=$mt" -F "path=$API_BACKEND_BASEPATH"
```

Seems like this option is adding url_rewriting policy, so this could be intended behavior.

**Comment by eguzki** [comment]
Yes, that is the intended behavior. The implementation is described here https://github.com/3scale/3scale_toolbox/issues/91#issuecomment-475641632
