### ISSUE TITLE
Import backend from OpenAPI

### ISSUE THREAD

**Issue by vishal41094** [3scale/3scale_toolbox#262]
It would be great to import Methods & Metrics in the Backends.

While doing an import from Swagger or OAS file, the methods & metrics should also get imported in the Backends as well along with the Product.

**Comment by eguzki** [comment]
Jira Issue: https://issues.redhat.com/browse/THREESCALE-6197

**Comment by lucamaf** [comment]
related to this one, sometimes you would like to import the Open API just as a Backend and without Product creation

**Comment by eguzki** [comment]
When several backends are imported and linked to a product, it would be very useful (I guess), to generate the OpenAPI doc for the whole product. The issue for that is https://github.com/3scale/3scale_toolbox/issues/277
