### ISSUE TITLE
To develop a sub-command in the existing command

### ISSUE THREAD

**Issue by vishal41094** [3scale/3scale_toolbox#264]
As the steps been already mentioned to develop a core command in 3scale-toolbox but it would be great if steps being mentioned to develop a sub-command in the existing command.

**Comment by eguzki** [comment]
This is what you are looking for? https://github.com/3scale/3scale_toolbox/blob/master/docs/plugins.md#plugin-subcommand

**Comment by vishal41094** [comment]
Yes,
I developed the same using the above URL as mentioned by you, but unable to execute the same, getting LoadError, as it is not getting loaded.
Could you please mention the steps to load as well for the same in the 3scale-toolbox.

Below is for your reference - 

C:\Users\vishal.rastogi>3scale import --help
Traceback (most recent call last):
        15: from C:/3scale-toolbox/bin/3scale:23:in `<main>'
        14: from C:/3scale-toolbox/bin/3scale:23:in `load'
        13: from C:/3scale-toolbox/embedded/lib/ruby/gems/2.5.0/gems/3scale_toolbox-0.16.0/exe/3scale:11:in `<top (required)>'
        12: from C:/3scale-toolbox/embedded/lib/ruby/gems/2.5.0/gems/3scale_toolbox-0.16.0/exe/3scale:6:in `suppress_warnings'
        11: from C:/3scale-toolbox/embedded/lib/ruby/gems/2.5.0/gems/3scale_toolbox-0.16.0/exe/3scale:11:in `block in <top (required)>'
        10: from C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from C:/3scale-toolbox/embedded/lib/ruby/gems/2.5.0/gems/3scale_toolbox-0.16.0/lib/3scale_toolbox.rb:26:in `<top (required)>'
         7: from C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         5: from C:/3scale-toolbox/embedded/lib/ruby/gems/2.5.0/gems/3scale_toolbox-0.16.0/lib/3scale_toolbox/commands.rb:3:in `<top (required)>'
         4: from C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         3: from C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         2: from C:/3scale-toolbox/embedded/lib/ruby/gems/2.5.0/gems/3scale_toolbox-0.16.0/lib/3scale_toolbox/commands/import_command.rb:3:in `<top (required)>'
         1: from C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/3scale-toolbox/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- 3scale_toolbox/commands/import_command/3scale_toolbox_plugin **(LoadError)**

**Comment by eguzki** [comment]
The `3scale_toolbox_plugin.rb` file should be dropped in any of the root paths of the LOAD_PATH. For example, if your file lives in `C:\myplugin`, then before running the CLI, add the following env var: `RUBYOPT=-I C:\myplugin`

**Comment by vishal41094** [comment]
Tried exceuting RUBYOPT=-I C:\myplugin, getting error as **'RUBYOPT' is not recognized as an internal or external command,
operable program or batch file.**, also changed the environment variables for the same, but couldn't get resolved.
Could you please help in the same.

**Comment by eguzki** [comment]
That `bash` way to set environment variable for the running command.

For windows, in powershell, it is done like this:

```
$Env:RUBYOPT = "-I C:\myplugin"
```

I tested it in windows recently and it is working
