### ISSUE TITLE
Update active docs fails on SaaS 

### ISSUE THREAD

**Issue by JillisTerHove-Rubix** [3scale/3scale_toolbox#280]
At this moment the update active docs step is failing after the initial import of an openapi spec. If you supply the access_token per the API documentation in the admin portal the call will succeed normally (1st, and subsequent uploads). I have a few commands already changed to take this argument and supply it to the active docs update. As this failure is in the path of a lot of commands and makes them not complete (skipping some important steps or not working at all). 

Is it a good idea to start changing the provider key over to access_tokens? Is it preferred to do this via an argument added to each call or is it preferred to use the same setup as with the provider key (in the URL). Will you accept commits for this?

**Comment by eguzki** [comment]
Thanks for the report. 

At this moment, I am getting 502 Bad Response when the list of active docs is requested with the provider key. As you say, with the access token, there is no issue.

```
<- "GET /admin/api/active_docs.json HTTP/1.1\r\nAccept: application/json\r\nContent-Type: application/json\r\nAuthorization: Basic MYTOKEN\r\nAccept-Encoding: identity\r\nUser-Agent: Ruby\r\nConnection: close\r\nHost: 3scale-supertest-admin.3scale.net\r\n\r\n"
-> "HTTP/1.1 502 Bad Gateway\r\n"
....
```

It can be easily reproduce with the simple `3scale activedocs list <remote>` command using the provider key as auth token.

However, this is not an issue of the toolbox, but of the 3scale API. In theory, you can use provider_key or access_token for all the commands of the toolbox. JFYI, the 3scale API has few endpoints that only accept access_token (Personal Access Token endpoints), but currently none of those are used by the 3scale Toolbox. So no issues should be expected. 

II have just opened jira issue, and the 3scale API team will fix it.

https://issues.redhat.com/browse/THREESCALE-6625

**Comment by eguzki** [comment]
In the toolbox doc it is specified that both provider key and access token are valid tokens to be used. And access tokens are preferred as they are more dynamic and they can be revoked easily.

https://github.com/3scale/3scale_toolbox/blob/master/docs/remotes.md#remote-urls

**Comment by eguzki** [comment]
Closing this issue as 3scale toolbox cannot do anything about this. Please, track https://issues.redhat.com/browse/THREESCALE-6625 for the issue.

**Comment by eguzki** [comment]
I just closed https://issues.redhat.com/browse/THREESCALE-6625.

Access tokens should be used. The use of provider keys is discouraged
