### ISSUE TITLE
On Windows, /dev/null causes E_UNKNOWN error.

### ISSUE THREAD

**Issue by leathersole** [3scale/3scale_toolbox#289]
https://github.com/3scale/3scale_toolbox/blob/dbdbda74a18ecf7af5026cebd48338786198ba35/lib/3scale_toolbox/commands/product_command/import_command.rb#L31

```
  "code": "E_UNKNOWN",
  "message": "No such file or directory @ rb_sysopen - /dev/null",
  "class": "Errno::ENOENT",
  ```

**Comment by miguelsorianod** [comment]
Hi @leathersole,

Thanks for reporting this.

I've opened a PR with a fix for it in https://github.com/3scale/3scale_toolbox/pull/290
