### ISSUE TITLE
copying to the same Target returns error

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale_toolbox#29]
One of the typical usage of this tool is to make an exact copy of a service inside the same instance to a new service (example: sandbox and production API).
At the moment this is not working:
command launched:
`3scale copy service 2555417745587 --source=https://ff82a5028dadc157e8925a875ae81fa1@alpha-bank-admin.3scale.net --destination=https://ff82a5028dadc157e8925a875ae81fa1@alpha-bank-admin.3scale.net`

error returned:
```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/local/share/gems/gems/3scale-api-0.1.4/lib/3scale/api.rb:8: syntax error, unexpected ',' (SyntaxError)
    def self.new(endpoint:, provider_key:)
                           ^
/usr/local/share/gems/gems/3scale-api-0.1.4/lib/3scale/api.rb:14: syntax error, unexpected keyword_end, expecting end-of-input
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/3scale_toolbox-0.2.2/exe/3scale-copy:73:in `<main>'
```

**Comment by mikz** [comment]
@lucamaf you need ruby >= 2.1 (https://github.com/3scale/3scale_toolbox/issues/24, https://github.com/3scale/3scale_toolbox/pull/25)
