### ISSUE TITLE
v.18.0 Error create method step

### ISSUE THREAD

**Issue by misanche** [3scale/3scale_toolbox#291]
Hi, first of all, congrats for the hard work done with the toolbox.

I have been testing the v18 with jenkins pipelines, and I have been facing some issues with this version, the first time that a service is created, it works fine, but if you run it again it fails importing the openapi spec. The same pipeline using the v0.17.1 version works fine.

Currently I'm using 3scale 2.9 on prem.

`[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:39:in 'initialize': Permission denied @ rb_sysopen - crash.log (Errno::EACCES)
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:39:in 'open'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:39:in 'print_unexpected_error'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:25:in 'handle_error'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:13:in 'rescue in error_watchdog'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:9:in 'error_watchdog'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:5:in 'error_watchdog'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli.rb:44:in 'run'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/exe/3scale:15:in '<top (required)>'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/bin/3scale:23:in 'load'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/bin/3scale:23:in '<main>'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:26:in block in methods_index': undefined method []' for #<ThreeScaleToolbox::Entities::Method:0x0000560a28ed7578> (NoMethodError)
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:25:in 'each'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:25:in 'each_with_object'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:25:in 'methods_index'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:31:in 'block in missing_operations'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:31:in 'reject'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:31:in 'missing_operations'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb:9:in 'call'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi.rb:63:in 'each'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/commands/import_command/openapi.rb:63:in 'run'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/cri-2.15.11/lib/cri/command_runner.rb:34:in 'call'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/cri-2.15.11/lib/cri/command_dsl.rb:294:in 'block in runner'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/cri-2.15.11/lib/cri/command.rb:362:in 'run_this'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/cri-2.15.11/lib/cri/command.rb:298:in 'run'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/cri-2.15.11/lib/cri/command.rb:316:in 'run'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/cri-2.15.11/lib/cri/command.rb:316:in 'run'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli.rb:47:in 'block in run'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:5:in 'block in error_watchdog'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:11:in 'error_watchdog'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli/error_handler.rb:5:in 'error_watchdog'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/lib/3scale_toolbox/cli.rb:44:in 'run'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/gems/3scale_toolbox-0.18.0/exe/3scale:15:in '<top (required)>'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/bin/3scale:23:in 'load'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] 	from /usr/local/bundle/bin/3scale:23:in '<main>'
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] Updated service id: 12, name: Todo List (v1.0.0)
[logs:pod/user1-todo-app-pipeline-2-import-openapi-7bft4] Service proxy updated`

Link to Jenkinsfile: 

https://raw.githubusercontent.com/misanche/3scaleworkshop-todo-app/main/Jenkinsfile

Link yo Openapi spec:

https://github.com/misanche/3scaleworkshop-todo-app/blob/main/src/openapi/openapi.yaml

I have not been able to run locally the v18 because there is no client for mac at the moment.

**Comment by miguelsorianod** [comment]
Hi @misanche,

Thanks for reporting the issue. We have reproduced the issue and created and merged a PR to fix it. A new release v0.18.1 has been created to include the change.

Let me know if the change has solved the issue.

Thank you.

**Comment by eguzki** [comment]
Fixed in #292
