### ISSUE TITLE
 Enable ppc64le arch on 3scale_toolbox

### ISSUE THREAD

**Issue by Abhijit-Mane** [3scale/3scale_toolbox#301]
Hi,

Thanks for the very well articulated documentation that helped build 3scale_toolbox from source and run the tests outlined
successfully on IBM Power architecture (in short, ppc64le).

**What is IBM Power architecture?**
It is a RISC architecture and is IBM's prodigy, IBM has recently made its ISA (Instruction Set Architecture) opensource and in doing
so, they have significantly contributed back to the opensource community at large. Many of the pioneers of banking and HPC
industries today run on ppc64le architecture.

As an ongoing effort to enable open-source projects to which ppc64le architecture can add value, we are trying to enable this
project. We have seen absolutely no deviation in build/test instructions. I plan to submit a PR to enable build/testing on ppc64le.

**What would it take from us to enable ppc64le in the CI/CD pipeline?**
I see CircleCI is being used for the CI pipeline of this project. As of now, this is not supported for native compilation on ppc64le.
However, currently, we are enabled/certified on Travis & Jenkins and lots of open source communities have successfully used these
as CI/CD for ppc64le.

**Comment by Abhijit-Mane** [comment]
Hello @eguzki 
Would like to get your view on whether we can have a travis CI/CD setup for ppc64le.

**Comment by eguzki** [comment]
Sure!  

What do you have in mind? Running the tests in ppc64le arch? good to have it.

We are maintaining not supported (community) 3scale toolbox installing packages https://github.com/3scale-labs/3scale_toolbox_packaging. Feel free to have a look and maybe it is also interesting to build a ppc64le installable.

Feel free to add PR.

**Comment by Abhijit-Mane** [comment]
Thanks @eguzki
Attached is a set of .travis.yml and supporting scripts. I tested these on https://travis-ci.com where I can link my fork of upstream
3scale_toolbox. I am able to successfully build it for ppc64le and also run tests. They use the ENDPOINT & PROVIDER_KEY you
had given us for testing (refer attached zip for details).

Please let me know what you think and I can submit a PR for incorporating these.
[travis.zip](https://github.com/3scale/3scale_toolbox/files/6608499/travis.zip)

**Comment by eguzki** [comment]
Hi, 

* I have revoked the access token you have been used as you have published it in the zip file and should not be public. Get in touch internally and I can provide another one for you.
* In the travis configuration, in the `before_install` process you do:
```
# install needed packages 
sudo apt-get update       
```
That command does not install needed packaged, just rebuilds internal package list database

* Please open PR with the e2e testing in ppc64le. I suggest we keep circleCI as it is and add travisCI with the ppc64le build configuration
