### ISSUE TITLE
Old mapping rules aren't replaced when importing a product

### ISSUE THREAD

**Issue by bthdimension** [3scale/3scale_toolbox#306]
When importing a pre-existing product with different mapping rules, I expect the new product definition to completely replace the old one. Instead, the new mapping rules are added to the old ones. We are left with a product that contains both the old unwanted mapping rules and the new mapping rules. If gone unnoticed, this is a potential security risk.

**Comment by eguzki** [comment]
which command are you using?

**Comment by eguzki** [comment]
* `3scale product copy` (as [documented](https://github.com/3scale/3scale_toolbox/blob/master/docs/copy-product.md)), `product mapping rules: Only missing mapping rules will be created.`. For this use case, please open RFE and the command can add flag to completely replace the old ones.
*  `3scale import openapi` (as [documented](https://github.com/3scale/3scale_toolbox/blob/master/docs/openapi.md)), `All existing mapping rules are deleted before importing new API definition. Methods not deleted if exist before running the command.`

We need to know what command you are using to know if this is a bug.

Please, provide toolbox version so we can reproduce the issue.

**Comment by bthdimension** [comment]
Thanks for the reply. I'm using "3scale product import" with Version v0.18.0.

**Comment by bthdimension** [comment]
To give a bit of background:
In my opinion, the whole point of importing from a yaml file should be to create or recreate the exact state of the product as defined in said file. This allows to fix a configuration, if someone messed it up by mistake. As an example, if someone added mapping rules that expose senstive endpoints, importing from the yaml should replace these harmful configurations with the correct ones. At the moment, this is not the case.
If this is the intended behavior, it would be helpful to at least have an option to "replace" instead of "add".  
Thank you very much! :-)

**Comment by eguzki** [comment]
More than reasonable. 

I will fix it.

**Comment by bthdimension** [comment]
Cool, thank you! :-)
