### ISSUE TITLE
complete duplication of a service

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale_toolbox#32]
the following settings are not copied when copying a service:
the base path, integration mode and API authentication are not copied to the new service.

Ideally the tool would be used to have a full duplicate and then just modify the staging and production endpoints.

**Comment by eguzki** [comment]
Opened issue on *porta* related to this issue:
https://github.com/3scale/porta/issues/133

**Comment by eguzki** [comment]
https://github.com/3scale/3scale_toolbox/pull/64 fixes about 
* integration mode (deployment_mode)
* API authentication (backend_version)

Still missing base path, proxy settings. WIP

**Comment by eguzki** [comment]
Base path, proxy settings and proxy settings are being copied. 

I guess all attributes you requested are being copied. Can you verify @lucamaf ?

Try HEAD from upstream:

Ruby >= 2.3 required
```
$ git clone git@github.com:3scale/3scale_toolbox.git
$ cd 3scale_toolbox
$ gem build 3scale_toolbox.gemspec
$ gem install 3scale_toolbox-0.4.0.gem
```
