### ISSUE TITLE
valid oas3 spec leads to require default credentials error

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale_toolbox#332]
first error is when importing due to the presence of security section which is completely standard, specifying to which part of the api, apikey authentication applies

  "components":{
    "securitySchemes":{
      "ApiKeyAuth":{
        "type":"apiKey",
        "in":"header",
        "name":"X-API-KEY"
      }
    }
  },
  "security":[
    {
      "ApiKeyAuth":"[]"
    }
  ]
}

second error is complaining about 
`User key must be provided by --default-credentials-userkey optional param
`
while apikey section is provided, meaning a default userkey shouldn't be needed

**Comment by eguzki** [comment]
I am afraid it is not a valid OAS3 doc.

The toolbox gives a hint:

```
3scale import openapi -d supertest - << EOF
> ---
> openapi: "3.0.0"
> info:
>   title: "some title"
>   description: "some description"
>   version: "1.0.0"
> paths:
>   /pet:
>     get:
>       operationId: "getPet"
>       responses:
>         405:
>           description: "invalid input"
> components:
>   securitySchemes:
>     ApiKeyAuth:
>       type: apiKey
>       in: header
>       name: X-API-KEY
> security:
>   - ApiKeyAuth: '[]'
> EOF
{
  "code": "E_3SCALE",
  "message": "OpenAPI schema validation failed: The property '#/security/0/ApiKeyAuth' of type string did not match the following type: array",
  "class": "ThreeScaleToolbox::Error"
}
```

The value of the "ApiKeyAuth" key cannot be a string,  Must be an array.

When the OAS doc is fixed:

```
3scale import openapi -d supertest - << EOF
---
openapi: "3.0.0"
info:
  title: "some title"
  description: "some description"
  version: "1.0.0"
paths:
  /pet:
    get:
      operationId: "getPet"
      responses:
        405:
          description: "invalid input"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - ApiKeyAuth: [] 
EOF
Created service id: 2555417922025, name: some title
Service proxy updated
destroying all mapping rules
Created GET /pet$ endpoint
```

**Comment by lucamaf** [comment]
you are right, I'm facing a similar problem to the second one highlighted, even though I have the apikey security configured , it is asking me for default credentials
https://studio-ws.apicur.io/sharing/354349f8-1ce4-4056-ac53-5c56ec5318a1

**Comment by eguzki** [comment]
That is because the OAS doc specifies the security definitions, but it does not specify security requirements. It is like you are declaring the auth method, but you do not say where it should be applied. 

The toolbox reads this OAS doc as "open API", hence it request you  for default credentials (3scale does not support open APIs)

**Comment by lucamaf** [comment]
What about the definition I just copied above, that applies to each path a security rule, no?

**Comment by eguzki** [comment]
> What about the definition I just copied above, that applies to each path a security rule, no?

Yes, but it is invalid.

**Comment by lucamaf** [comment]
no, it is not, just verified on editor.swagger.io

**Comment by eguzki** [comment]
your spec is like this:
```json
security":[
{
"ApiKeyAuth":"[]"
}
]
```

This is invalid. Check [OpenAPI 3 security req object spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#security-requirement-object). It must be:

```
security":[
{
"ApiKeyAuth": []
}
]
```

**Comment by lucamaf** [comment]
I meant the one above in the link , on apicur.io , based on oas2
attached now

**Comment by eguzki** [comment]
The OAS doc from https://studio-ws.apicur.io/sharing/354349f8-1ce4-4056-ac53-5c56ec5318a1 specifies the security definitions, but it does not specify security requirements.

You need to add the security requirements: 
```json
"security": [
  {
    "api_key": []
  }
]
```
With that you are specifying: 'apply the security definition called "api_key" to all operations'

**Comment by lucamaf** [comment]
this is alternative to having that at the operations level, IMO it is a limitation that should be highlightd in the import of swagger spec

**Comment by eguzki** [comment]
It is documented in upstream (https://github.com/3scale/3scale_toolbox/blob/main/docs/openapi.md#authentication)

```
Authentication

Just one top level security requirement supported. Operation level security requirements are not supported.
```

**Comment by eguzki** [comment]
It is based on the 3scale model. 3scale does not allow sec requirement at operation level. It only allows one global sec requirement.

**Comment by lucamaf** [comment]
sorry I missed that ...
