### ISSUE TITLE
Override private base url not working

### ISSUE THREAD

**Issue by telapo** [3scale/3scale_toolbox#379]
I am trying to import an openapi definition using 3scale toolbox, but I am getting the following error:

```shell
{
  "code": "E_INVALID_URL",
  "message": "invalid url: /api",
  "class": "ThreeScaleToolbox::InvalidUrlError"
}
```

The command I am using is:

```shell
 docker run -v $PWD/sample-openapi.json:/tmp/openapi.json toolbox 3scale import openapi -d oc --backend /tmp/openapi.json --override-private-base-url=http://real-url/api -k
```

The servers section of the openapi specification looks like this:

```json
 "servers" : [ {
    "url" : "/api",
    "description" : "Relative path based on location of deployment"
  } ],
```

It seems that the problem is the fact that it is a relative url, as the use of `--override-private-base-url` seems to be completely ignored by the toolbox. If I try to change it to an absolute url (e.g. http://etc../api), it does work; however, the current format allows me to use swagger under multiple domains without having to hardcode a value for each one of them.

Is there anything that I can do or the toolbox requires a proper url to override it?

**Comment by eguzki** [comment]
Hi, thanks for reporting. 

Relative URLS in servers were never supported/tested. https://github.com/3scale/3scale_toolbox/pull/380 should do that
