### ISSUE TITLE
Command to import service using OpenAPI / Swagger spec or RAML format

### ISSUE THREAD

**Issue by eguzki** [3scale/3scale_toolbox#38]
Using an API definition format like OpenAPI / Swagger or RAML you can automate some setups and save a lot of time in configuration.

When you import an API defintion, the following actions will be performed in the background:

1. Create a new service (unless you specify one)
1. Create methods in the 'Definition' section
1. Attach newly created methods to the 'Hits' metric
1. Create mapping rules and show them under API > Integration

**Comment by andrewdavidmackenzie** [comment]
I'd scope the issue to focus on Open API Spec.
RAML, if desired, could be done as a separate effort.
