### ISSUE TITLE
Comand to create, list, show, update, and delete services

### ISSUE THREAD

**Issue by eguzki** [3scale/3scale_toolbox#40]
Lower level command for service management

**Comment by sgutierr** [comment]
3scale-cli older capability of managing services in 3scale, very useful for showing information about which services are configured in a 3scale instance

**Comment by eguzki** [comment]
@sgutierr  Thanks to @miguelsorianod  you can now manage services in 3scale with service commands

Feedback more than welcome!

Closing this issue
