### ISSUE TITLE
Framework to make it easy adding new commands

### ISSUE THREAD

**Issue by eguzki** [3scale/3scale_toolbox#48]
Avoid argument duplication in new commands, leverage general commands and methods to set tokens, endpoints.

- Fully POSIX-compliant flags
- Nested subcommands
- Easy generation of commands
- Modular system based on plugins

**Comment by mikz** [comment]
https://devcenter.heroku.com/articles/heroku-cli is great example of how to make CLI [with plugins](https://devcenter.heroku.com/articles/using-cli-plugins).

They extracted the framework: [oclif](https://oclif.io). Yes, it is JavaScript. 

Maybe [hanami/cli](https://github.com/hanami/cli) could be good enough in Ruby.

**Comment by eguzki** [comment]
I was reviewing [Thor](https://github.com/erikhuda/thor)

Seems to meet expectations. Full fledged, flexible and active project. Bundler use it.

**Comment by mikz** [comment]
Also pretty much inactive: https://github.com/erikhuda/thor/blob/master/CHANGELOG.md + https://github.com/erikhuda/thor/releases
Rails uses it too, but every time I do use Thor I feel like it is path to hell because there is no way to push changes upstream.

**Comment by eguzki** [comment]
Another option could be [clamp](https://github.com/mdub/clamp)

Plugin support from heroku is great. However I was thinking about the value added to our use case. I see the advantages, but could be too much work when 99% of the cases 3scale CLI installations will require all commands and subcommands installed. The only advantage would be independent release management of the plugins and the core project.

Besides, in heroku CLI, [plugins](https://devcenter.heroku.com/articles/using-cli-plugins) are supported by *oclif's* [plugin system](https://oclif.io/docs/plugins.html). I cannot find any CLI framework in ruby with plugin support. We would have to implement it from scratch. It is doable, though. Starting from simple model and iterating to more advanced uses cases.

**Comment by eguzki** [comment]
[Thor](https://github.com/erikhuda/thor) has 10 years of activity, [hanami-cli](https://github.com/hanami/cli) just one year. I see your concern about pushing changes to upstream. That's definitely not good. But I tend to prefer stability. 

Both meet minimal functional requirements. 

From rubygems.org: 
Thor -> 185,693,349 downloads
Hanami-cli -> 20,952 downloads

**Comment by mikz** [comment]
@eguzki I made quite a few projects with thor, including multi subcommand CLI. It is fine for small things. For scaffolding too. But once you want to test it or use submodules it quite falls apart.

https://github.com/search?p=5&q=org%3A3scale+thor&type=Code
https://github.com/search?p=4&q=thor+org%3Amikz&type=Code

Plugin system has more benefits than just independent release cycles. It offers flexibility and customization. People are free to use the same interface to write own commands. Possibly useful only for internal use cases and then install them privately.

Stability is quite different from a frozen project. You can have progress and stability. My point is that whatever you don't like about Thor later down the road is likely not going to change in the future.

Also I was mentioning oclif is just to give some food for though if Ruby is the right choice. For example https://github.com/zeit/pkg is quite trivial way how to deliver the CLI to customers.

Regarding those numbers. Thor is rails dependency, so obviously it is incomparable.

**Comment by eguzki** [comment]
Thor is definitely not frozen. It has releases yearly :) After several years the project is mature and I guess critical bugs drop and need for new features decreases.

Ruby seems to be the choice. I proposed Go (as Openshift client and trending in RH). I have experience in Go as well. The reasoning for reject was: people in RH know about ruby and may be easier to contribute. Besides, the API client [3scale-api-ruby](https://github.com/3scale/3scale-api-ruby) is written in Ruby. 

Regarding your reluctance to use Thor, I guess we will have to give it a try to something else :)

**Comment by eguzki** [comment]
[RubyGems plugin API](https://guides.rubygems.org/plugins/) seems to be great for making CLI with plugins.

**Comment by mikz** [comment]
Yes. It is ok. Current plugin API (https://github.com/3scale/3scale_toolbox/commit/e8eeebcea381e236f1ce01cccb62bdfcda8515a2) is not that different. It just expects gems to be named `3scale*`.

However, when packaged with travelling ruby or similar it will be harder to install plugins. 
I quite like the idea of `link` of heroku-cli that makes some plugin available. The idea behind the current design was that subcommands are just executables, so they can be in any language.

If there something I'd push for, then it would be good design for good modular system.
I'd consider good modular system similar to the current one where subcommands are just executables in some libexec folder. Then they can be installed/linked like https://devcenter.heroku.com/articles/developing-cli-plugins#installing-the-plugin
And the master command could communicate parsed options or stored credentials to subcommands by ENV variables. Most or all bundled subcommands could be written in Ruby, using the same libraries, but there would be an option to do whatever you want. 
Or something like https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/ makes a lot of sense (so they can show all the flags from the master command because they are in yaml).

**Comment by eguzki** [comment]
For development, in rubgygems plugin api, the analogue of ```heroku plugins:link``` would be
```
RUBYOPT=-Ilib gem
```
The builtin mechanism of ruby, no need to reinvent the wheel. For packaging, it should work as well.

Regarding good modular system, completely agree. Modularity, yes, but up to some extent. Subcommands being executables, IMO, makes them very isolated from each other, too much. Using ENV vars as communication pipe might be limiting. I was thinking on sharing kind of context with login information, remotes info (currently URI and provider key) like git remotes or even connection interface object and other useful info. Besides, easier to share helper toolbox for all kind of operations like parsing.

**Comment by unleashed** [comment]
I'd also suggest checking out the design of [clap](https://clap.rs) for ideas/inspiration, as it has had a significant evolution.

**Comment by eguzki** [comment]
implemented in #50

**Comment by eguzki** [comment]
implemented in #51
