### ISSUE TITLE
3scale update service errors

### ISSUE THREAD

**Issue by shannon** [3scale/3scale_toolbox#57]
When running the `3scale update service` command I receive the following error:

```bash
3scale update service 2555417742467 2555417759842 -s https://xxxxxxxxxxxxxx@domain-admin.3scale.net -d https://xxxxxxxxxxxxxxx@domain-admin.3scale.net
updating service settings for service id 2555417759842...
Traceback (most recent call last):
        2: from /home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:259:in `<main>'
        1: from /home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:235:in `update_service'
/home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:106:in `copy_service_settings': undefined method `update_service' for #<ThreeScale::API::Client:0x000056014c987b70> (NoMethodError)
Did you mean?  update_proxy
```

If I pass the --rules-only flag the update seems to work ok.

**Comment by eguzki** [comment]
Hi Shannon, 

*update service* command is not released yet. It is not yet available in required [3scale-api](https://github.com/3scale/3scale-api-ruby) dependency, although implemented and merged in master branch. See missing unreleased features from [changelog](https://github.com/3scale/3scale-api-ruby/blob/b6d4b09b9f9353a7c31043f826db039bc8a8664e/CHANGELOG.md#unreleased).

However, you can build yourself latest version from master *HEAD* and try it. 
```
gem build 3scale-api.gemspec
gem install 3scale-api-*.gem
```

I have done it myself and works as expected (as far as I tested). 

We will be releasing 1.6 of 3scale-api ASAP. There is already an [issue](https://github.com/3scale/3scale-api-ruby/issues/35) opened for that. This issue has been open for too long already. I'll be on this ASAP.

**Comment by eguzki** [comment]
3scale-api release 1.6: https://github.com/3scale/3scale-api-ruby/pull/39
3scale_toolbox release 0.5.0 with support for update service: https://github.com/3scale/3scale_toolbox/pull/54

@shannon I close the issue, reopen it if you have any issue
