### ISSUE TITLE
RFE: Add ability to update certain parts of a service

### ISSUE THREAD

**Issue by shannon** [3scale/3scale_toolbox#58]
Right now there is a `--rules-only` flag for `3scale update service` which normally works great, but if a method exists in source but not in the destination it will throw an error:

```bash
the source service has 2 mapping rules
the target has 0 mapping rules
missing 2 mapping rules
Traceback (most recent call last):
        4: from /home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:257:in `<main>'
        3: from /home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:226:in `copy_mapping_rules'
        2: from /home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:226:in `each'
        1: from /home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:228:in `block in copy_mapping_rules'
/home/rhuser/.gem/ruby/gems/3scale_toolbox-0.4.0/exe/3scale-update:228:in `fetch': key not found: 2555418096690 (KeyError)
Did you mean?  2555418015767
```

This makes some sense but there is no way to copy the rules AND methods over to get around this. You have to manually create new methods on the destination first.

The use case here is to create a staging service and a production service that are connected to different backends. And then have a simple way to keep the mapping rules/methods in sync while not wiping out the Private Base URL or other settings.

**Comment by eguzki** [comment]
We opened issues for implementing commands that manage (create, list, update, delete) components of higher level entities like services. 

This issue is for [methods](https://github.com/3scale/3scale_toolbox/issues/43) and this issue is for [rules](https://github.com/3scale/3scale_toolbox/issues/42).

When implemented (ASAP), you will be able to keep sync'ed mapping rules/methods of services.

**Comment by eguzki** [comment]
This issue has indirectly been fixed with new 3scale APIaP model.
