### ISSUE TITLE
SSL Error while copying the service

### ISSUE THREAD

**Issue by mohansidda** [3scale/3scale_toolbox#59]
I am trying to copy the service from one environment to another environment running the similar command : 
3scale copy service NUMBER --source=https://provider_key@foo-admin.3scale.net --destination=https://provider_key@foo2-admin.3scale.net

I am getting the following error : 
<-----
5.2/bin/ in PATH, mode 040777
Traceback (most recent call last):
	9: from /usr/local/lib/ruby/gems/2.5.0/gems/3scale_toolbox-0.4.0/exe/3scale-copy:87:in `<main>'
	8: from /usr/local/lib/ruby/gems/2.5.0/gems/3scale-api-0.1.5/lib/3scale/api/client.rb:16:in `show_service'
	7: from /usr/local/lib/ruby/gems/2.5.0/gems/3scale-api-0.1.5/lib/3scale/api/http_client.rb:34:in `get'
	6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:1213:in `get'
	5: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
	3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:981:in `connect'
	1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain) (OpenSSL::SSL::SSLError)

----->

I am using clusterup OCP environment (self-signed certificates). Any suggestions on how to fix this?

**Comment by mikz** [comment]
@mohansidda can you set `SSL_CERT_FILE` environment variable pointing to the self-signed certificate? 

You can get the remote host certificate by using OpenSSL on CLI:

```shell
echo | openssl s_client -showcerts -servername self-signed.badssl.com -connect self-signed.badssl.com:443 2>/dev/null | openssl x509
```

Store it in some file and then try:

```shell
SSL_CERT_FILE=cert.pem ruby -r net/http -e 'puts Net::HTTP.get_response(URI("https://self-signed.badssl.com")).code'
```

You can also make your Ruby install permanently trust this certificate by adding it to the trusted certificates directory. 

Documentation on the format of certificates stored in that directory: https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_load_verify_locations.html
https://www.openssl.org/docs/man1.1.0/apps/c_rehash.html

How to get the all-in-one file and the certificate directory: 

```shell
ruby -ropenssl -e 'p OpenSSL::X509::DEFAULT_CERT_DIR'
ruby -ropenssl -e 'p OpenSSL::X509::DEFAULT_CERT_FILE'
```

**Comment by mikz** [comment]
@yohanesws disabling the TLS verification is a bad idea. You should exchange the public keys and then just verify them.

I see your certificate is actually a chain, not a pure self-signed certificate. Here is an updated method of getting the certificate chain:

```shell
echo | openssl s_client -showcerts -servername $host -connect $host:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
```

However, your example would fail anyway, because the domain does not match the certificate:

```
SSL_CERT_FILE=cert.pem curl -v https://$host/                                                                                                                           
*   Trying 34.214.179.239...
* TCP_NODELAY set
* Connected to 3scale-admin.5e1f.apps.rhpds.openshift.opentlc.com (34.214.179.239) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /Users/mikz/Downloads/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.apps.rhpds.openshift.opentlc.com
*  start date: Dec  7 12:57:23 2017 GMT
*  expire date: Dec  7 12:57:24 2019 GMT
*  subjectAltName does not match 3scale-admin.5e1f.apps.rhpds.openshift.opentlc.com
* SSL: no alternative certificate subject name matches target host name '3scale-admin.5e1f.apps.rhpds.openshift.opentlc.com'
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name '3scale-admin.5e1f.apps.rhpds.openshift.opentlc.com'
```

Curl is right to say `does not match 3scale-admin.5e1f.apps.rhpds.openshift.opentlc.com` because `subject: CN=*.apps.rhpds.openshift.opentlc.com`. There is an extra layer of one wildcard in between.

I get the same error from Ruby:

```shell
SSL_CERT_FILE=cert.pem ruby -r net/http -e "puts Net::HTTP.get_response(URI(%Q{https://$host})).code"
```

**Comment by yohanesws** [comment]
@mikz That make a sense, so there a extra layer in wildcard certificates.

Let me try to change the certificates and testing again

**Comment by mohansidda** [comment]
Its working now. we can close the issue. 

Thanks, @mikz and @yohanesws

**Comment by mikz** [comment]
I'd like to transform this into a documentation update before we close the issue. 
Self signed certificates are very common in these environments, so we should provide clear instructions on how to work with it.
