### ISSUE TITLE
Copying services:  ability to set the system name of the target service

### ISSUE THREAD

**Issue by vramosp** [3scale/3scale_toolbox#8]
### Problem
When copying a service, the system name is read only and if you do it within the same account, you have two services with the same system name.

### Suggested solution
Add a command line switch --target-system-name=. The other fields can be changed manually as they're not read only.

### Notes
Right now when services are copied to a different account, the system_name is the same as the original (without "_copy").

**Comment by macejmic** [comment]
@3scale/support @vramosp 

new release according this change: https://rubygems.org/gems/3scale_toolbox/versions/0.2.1
