### ISSUE TITLE
RFE: Create an ActiveDocs with updated environmental fields when importing a service from OpenAPI

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/3scale_toolbox#90]
# Current Situation

When importing a service from an OpenAPI Specification, using:

```sh
3scale import openapi -t echo_api -d https://$ACCESS_TOKEN@$TENANT-admin.3scale.net examples/echo-api.yaml
```

The service is created but no ActiveDocs is created. 

# Proposed Changed

The OpenAPI Specification used to create the service is pushed as an ActiveDocs file, using the same system_name as the service. 

This OpenAPI Specification is patched to take into account the new environment: 
- the `host` field is updated with the hostname component of the public production base URL
- the `schemes` field is updated with the scheme component of the public production base URL
- the `basePath` field is updated if rewriting rules have been set
- the `securityDefinitions/*/authorizationUrl` and `securityDefinitions/*/tokenUrl` fields are updated with the token and authorize endpoints listed in the OpenID Connect wellknown endpoint (when OIDC is in use)

# Business need

Currently, the missing ActiveDocs implies for the customer to have a tedious manual step to update the OpenAPI Spec and upload it. This is needed to achieve a "ready-to-use" API on the Developer Portal.

This is something I'm currently doing in the [Ansible playbooks](https://github.com/nmasse-itix/threescale-cicd/blob/f22a0fc3cb70f91cc6edc11117bb14f3940b5730/templates/rewritten_openapi.j2).

**Comment by sgutierr** [comment]
Older CLI tool offered this feature
