### ISSUE TITLE
RFE: Set the correct security scheme when importing an OpenAPI Specification

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/3scale_toolbox#92]
# Current Situation

Currently, when importing a new service from an OpenAPI with:

```sh
3scale import openapi -t echo_api -d https://$ACCESS_TOKEN@$TENANT-admin.3scale.net examples/echo-api-oidc.yaml
```

The service is created with API Key security even if the OpenAPI Specification mandates OpenID Connect and I found no specific way to override this from the command line. 

See this sample OpenAPI Specification: [echo-api-oidc.yaml](https://github.com/nmasse-itix/threescale-cicd/blob/f22a0fc3cb70f91cc6edc11117bb14f3940b5730/tests/test-cases/api-contracts/echo-api-oidc.yaml#L29-39). 

# Proposed Change

The 3scale toolbox looks for the `securityRequirements` and `securitySchemes` fields to determine the kind of security to apply and sets it accordingly when creating or updating the service.

The current logic that I'm using in the Ansible playbooks are:
 - I'm looking for the global security requirements and I require to have one and only one requirement
 - I'm searching for the matching security scheme
 - I'm determining whether the scheme is API Key or OIDC (the two we are supporting in 3scale)

If there is no security requirement, we can consider it as an "Open API" and add the [default_credentials policy](https://github.com/3scale/apicast/tree/master/gateway/src/apicast/policy/default_credentials) to the policy chain. 

# Business Justification

One of our customer is using exclusively OpenID Connect APIs and thus cannot use the 3scale toolbox to provision its APIs.

**Comment by sgutierr** [comment]
OIDC atuhtentication protocol is supported by 3scale and used by users.

**Comment by nmasse-itix** [comment]
The OIDC Issuer Endpoint contains sensitive information (the RH-SSO client_id and client_secret that has admin privileges on the SSO realm). So, we cannot take this information from the OpenAPI specification (which is usually committed in a git repo which is even sometimes public). 

Proposition: the OIDC Issuer Endpoint is taken from a command line parameter. 

However, we can extract from the OAS file: 
 - the scopes
 - the chosen OAuth flow

**Comment by eguzki** [comment]
Few questions (for now).
* For `apiKey` type, `Credentials location` is located in `in` field, hence, `header` or `query`. For `oauth2`, our `oidc`, we can assume `Credentials location` to be always `As HTTP Headers`. Is that correct?

* For a service in mode `OpenID Connect `, where do swagger scopes apply? do not see any service configuration for scopes.

**Comment by nmasse-itix** [comment]
> * For `apiKey` type, `Credentials location` is located in `in` field, hence, `header` or `query`. For `oauth2`, our `oidc`, we can assume `Credentials location` to be always `As HTTP Headers`. Is that correct?

For `oauth2`, yes it's fixed: in the HTTP Header "Authorization".

> * For a service in mode `OpenID Connect `, where do swagger security scopes apply? do not see any service configuration for scopes.

Scopes need to be defined using the `keycloak_role_check` policy (if the swagger `securityRequirements` are compatible with what the policy can do).

**Comment by eguzki** [comment]
More questions on `scopes`.

Can you elaborate more on this?
> swagger securityRequirements are compatible with what the policy can do

Something to do with flow? certain flows are not compatible with `keycloak_role_check` policy?
Can you provide documentation link where I can have some "specification" to implement?

Another question: for  `keycloak_role_check` policy configuration, scopes are configured as `realm_roles` or `client_roles`? Again, some documentation to know what to implement?

**Comment by eguzki** [comment]
When there is no security requirement in swagger spec, we can consider the service as an "Open API". Toolbox will then add `default_credentials` policy (also called as `anonymous_policy`) if not yet in policy chain (to be idempotent)

Anonymous policy has to be configured with `user_key`.
```json
{
  "name": "default_credentials",
  "version": "builtin",
  "configuration": {
    "auth_type": "user_key",
    "user_key": "2342423423424234"
  },
  "enabled": true
}
```

Proposal:
The value of that `user_key` will be read from optional param `--defaul-credentials-userkey`. Note that If swagger spec happens to lack security requirement and `--defaul-credentials-userkey` is NOT set in command, toolbox will raise error.

Future enhancement would be to check application for that `user_key` exists and create if it does not. But new problem comes up, which app plan attach to?

Does it make sense @nmasse-itix ?
