### ISSUE TITLE
Basic application plan for testing purposes when a swagger definition is importing

### ISSUE THREAD

**Issue by sgutierr** [3scale/3scale_toolbox#95]
It would be nice if toolbox provides a flag that creates a "Basic appliation plan" with all metrics and methods enabled (with out rate limits and price rules) when we are importing a swagger defintion. This is useful for quick API testing proposes.

**Comment by eguzki** [comment]
`3scale application-plan create [opts] <remote> <service> <plan-name>` command does what you ask.

https://github.com/3scale/3scale_toolbox/blob/master/docs/app-plan.md#create
