### ISSUE TITLE
RFE: API semantic versioning

### ISSUE THREAD

**Issue by sgutierr** [3scale/3scale_toolbox#96]
Version numbering allows the clear identification of built artefacts and their compatibility to their respective consumers. Semantic versioning’ which is based on 3 numbers and an alphanumeric string:
 [major] 	. 	[minor]	 .	 [patch]

- The major number is bumped up when an incompatible (ie. breaking) change has been made to the api from the previous version. So any developer planning to use this library can easily see that a breaking change has been included.
- The minor version is bumped up when a change has been made to the functionality within the artefact that is still backwards compatible. ie. the api has not been changed however the functionality is now different to previous.
I would focus on managing Major and Minor releases, that implies:
1. Major releases (**2**.0.0) : if toolbox detects a previous major release in 3scale, for instance already exists the release 1.x then -> Create a new services and import service specification.
2. Minor releases (1.**0.0**) : if toolbox detects this is minor upgrade, then rename older service in 3scale and reimport the Active Docs.

**Comment by andrewdavidmackenzie** [comment]
My opinion is that hard-coding this behaviour into the toolbox based just on the spec version number would be unexpected behaviour in some cases by customers, and would inflexible and not adapt to different customers' ways of handling versioning.

An update to a specified system_named service would change to be a create of a new service instead and then we'd have two services (would need to capture the new service's system_name?). 

You'd also lack control over the previous version and a separate command would be needed to delete the old one (when the customer decides to deprecate it).

If we added a flag to the toolbox to control this behaviour, then the caller of the toolbox (e.g. a Jenkins pipeline) would have to implement the logic to use the flag or not, thus externalizing part of the logic anyway. So it would be similar to implementing the logic there (outside the toolbox) to do an update or a create.

So, for me, the implementation that would make most sense would be for the toolbox to provide predictable primitive commands (i.e. NOT do this), and have this customer-dependant versioning logic outside of the toolbox (e.g. in a workflow, or jenkins pipeline) and invoke either an update or a create, with the OAI spec.

**Comment by sgutierr** [comment]
Semantic versioning has became an industry ipso facto standard approach to resolve the problem of managing API releases. I've seen that ALL companies with I've have been worked or they are already following semantic versioning or they are thinking to follow it. 
In my opinión this is one of the most important feature of Toolbox for these reasons:
- Everybody who implements an API Management solution must deal with the versioning topic. It doesn't make sense enforce all customers to develop its own semantic versioning, when this feature can be provided OOTB only once by the API Manager.
- API versioning is an important matter of the API Manager Platform, which it should provide a solution to handle all use cases (at least described in the standard semantic versioning). Jenkins orchestate deployments pipelines, promotions among environments, it isn't responsible for knowing how to replace a 3scale Active Docs.
-Current 3scale Ansible CICD playbook provides this feature OOTB, the feedback always has been positive for the useful capabilities. 
-Perform the same versioning mechanism for the whole company API Lifecycle.
-Regarding flexibility a flag disabling this behaviour would be enough, but at least from API Manager layer, we are providing a solution for dealing API versioning using the standar that almost everyone is using. 
Also there are business case a part of customer demand:
Benefits to implement this feature in Toolbox: we are talking about:
- Improving time to market (less time during 3scale implementation)
- Avoid developers error prone (avoid support cases)
- Less ramp up time to learn 3scale technology for partners or developers. Implementers don't have to know deeper 3scale techincal knowledge. 
- Rapid integration with current API backend lifecycle.

**Comment by vramosp** [comment]
I wouldn't hard code it, I would probably accept a version number optionally. If it's minor release then update, if it's major, then create new service. The param is optional so if not passed, by default always updates the service. The caller (e.g. Jenkins pipelines) would have to manage passing versions, yes.

**Comment by eguzki** [comment]
Will be implemented by 3scale API. Not a toolbox issue anymore

https://issues.redhat.com/browse/THREESCALE-2343
