### ISSUE TITLE
copy service  "-t" argument is confusing

### ISSUE THREAD

**Issue by alexh-cartera** [3scale/3scale_toolbox#99]
Documentation for "copy service" makes it appear as though the "-t" or "--target-system-name" argument is optional, but it appears to be required.  The purpose of this argument is also not very clear from the documentation.

It would be best if this argument was made optional and the tool re-used the system name from the source service by default.  The argument could then be used to override that behavior.

At the very least, please update the documentation to reflect the current behavior of the tool.

**Comment by lucamaf** [comment]
agreed
